# Generated by Django 3.2.7 on 2021-09-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('foto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('foto', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('descuento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PreOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.JSONField()),
                ('fecha', models.DateField()),
                ('periodo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('foto', models.CharField(max_length=500)),
                ('precio', models.FloatField()),
                ('rating', models.FloatField()),
                ('descripcion', models.TextField()),
                ('existencia', models.FloatField()),
                ('fecha_venc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.CharField(max_length=250)),
                ('pwd', models.CharField(max_length=250)),
                ('preorden', models.ManyToManyField(to='api.PreOrden')),
            ],
        ),
    ]
