# Generated by Django 3.2.7 on 2021-09-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoria'),
        ),
        migrations.AddField(
            model_name='venta',
            name='preorden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.preorden'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario'),
        ),
    ]
